### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by clearspear** [David-Lor/MQTT2ETCD#4]
Hi David, I'm working on a project involving MQTT and came across your repo. I was wondering if you could describe a scenario in which this MQTT to ETCD bridge would be used.

**Comment by David-Lor** [comment]
@ClearSpear to be honest, I do not have any useful, concrete examples.
It might be useful, for example, to use ETCD as storage backend for MQTT (mosquitto broker has its own storage backend, but for some reasons ETCD might be more useful).
Or, in general, you can just persist ETCD configurations through MQTT, without having to use the ETCD API (if you feel more comfortable using MQTT).
